### ISSUE TITLE
FastSimpleImport is not fast

### ISSUE THREAD

**Issue by nivida** [firegento/FireGento_FastSimpleImport2#36]
I have installed the FastSimpleImport and the demo from here. With your demo module and the original CLI commands you have created. An Import from one product has around to 30seconds.. is this the expected time?

CLI Print:

root@wps:/storage/var/www # bin/magento fastsimpleimportdemo:products:importsimple
Import started
1: Begin data validation
2: The validation is complete.
3: Checked rows: 1, checked entities: 1, invalid rows: 0, total errors: 0
4: Import data validation is complete.
1: Begin import of "catalog_product" with "append" behavior
2: Checked rows: 0, checked entities: 1, invalid rows: 0, total errors: 0
3: The import was successful.
Import finished. Elapsed time: 32.14s

**Comment by danslo** [comment]
ImportExport (and thus FastSimpleImport) isn't particularly fast for small datasets. The reason for this is that it has some overhead on startup (initialize category trees, attributes, etc etc etc).

For one of our projects we're doing 40k products in a couple of minutes (~15) with this module.

**Comment by nivida** [comment]
Thx for the reply :) 

After some tests i have the result you described above.. with 5000 Products i have 0.18s per product. What is the prefered way you choose to import products? Load Products from an mysql Table that our dataServer creates? Create an CSV with all Products for the import? Or should the dataServer insert the products in a redisDB to import in this? (maybe more speed)

**Comment by ankit-sf** [comment]
@nivida which method did you used?
Load Products from an mysql Table that our dataServer creates? Create an CSV with all Products for the import? Or should the dataServer insert the products in a redisDB to import in this? 

i am same issue for quite some time
because i created custom url for importing products but faces problem like timeout.
there is an option for enabling temp tables, but i don't know how to use that.

Thanks
