### ISSUE TITLE
Sequence import with different behavior does not work

### ISSUE THREAD

**Issue by aunts** [firegento/FireGento_FastSimpleImport2#4]
While doing two imports in row with different behavior second import is failing. In my example the first import with "add/update" is working fine. But second import fails because behavior "delete" is not taken. Instead second import is done with behavior "add/update" too. Thats wrong! Only running the "delete" part works fine.

I'm not sure. Seem's to be an magento bug? Or a firegento one?

/*\* @var \FireGento\FastSimpleImport2\Model\Importer $importerModel */
$importerModel = $this->_objectManager->create ( 'FireGento\FastSimpleImport2\Model\Importer' );
$importerModel->setBehavior ( Import::BEHAVIOR_ADD_UPDATE );
$productsArray = [
    [
        'sku' => 'firegento-test',
        'attribute_set_code' => 'Default',
        'product_type' => 'simple',
        'product_websites' => 'base',
        'name' => 'FireGento Test Product',
        'price' => '14.0000',
    ],
];
$importerModel->processImport ( $productsArray );

/*\* @var \FireGento\FastSimpleImport2\Model\Importer $importerModel */
$importerModel = $this->_objectManager->create ( 'FireGento\FastSimpleImport2\Model\Importer' );
$importerModel->setBehavior ( Import::BEHAVIOR_DELETE );
$deleteArray = [
    [
        'sku' => 'firegento-test'
    ],
];
$importerModel->processImport ( $deleteArray );

Any ideas/help?

**Comment by avstudnitz** [comment]
That has been a problem with the Magento 1 import as well - ImportExport is not designed to be run twice in a single request. This will probably need some work. If you'd provide a pull request, we'd be happy to merge it :-) If not, no problem, I suggest using two different requests then.

**Comment by aunts** [comment]
Hi, sorry for the late response. I would love to fix that issue and create a pull request. But, can you give me a hint how to do that best way? Thx

**Comment by EliasKotlyar** [comment]
Hello Aunts,

The behaviour is taken from:
Magento\ImportExport\Model\ResourceModel\Import\Data::getBehavior()

I havent investigated so much,but i suppose that this Model is saved somehow in the DB.  Because of that, it will be loaded only once. You will have to find this piece of code and manage it to run it twice.

If you are looking for a easy way to accomplish this : One quick&dirty solution might be to intercept this method and get the "behaviour" which you want from another place(Mage::registry if you think of M1)


Greetings
Elias
