### ISSUE TITLE
Di compilation issue on 2.0.11

### ISSUE THREAD

**Issue by redboxmarcins** [firegento/FireGento_FastSimpleImport2#40]
`php bin/magento setup:di:compile
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 26 secs 284.0 MiBMiB

                                                                     
  [ReflectionException]                                              
  Class Magento\Framework\EntityManager\MetadataPool does not exist  
                                                                     

                                                                     
  [ReflectionException]                                              
  Class Magento\Framework\EntityManager\MetadataPool does not exist  
                                                                     `

**Comment by EliasKotlyar** [comment]
Hello redboxmachine,

I have provided a fix for this issue. Please update the extension from the master branch and try again.

Greetings
Elias

**Comment by hostep** [comment]
Sorry, I didn't actually test this, but @EliasKotlyar, are you sure this is going to work? Because in Magento 2.0.x, the namespace [Magento\Framework\EntityManager](https://github.com/magento/magento2/tree/2.0/lib/internal/Magento/Framework/EntityManager) doesn't seem to exist. This was only introduced in [Magento 2.1.0](https://github.com/magento/magento2/tree/2.1/lib/internal/Magento/Framework/EntityManager).

So maybe the correct solution is to declare this module as not compatible with Magento 2.0.x ?

(but maybe I'm missing something and then you can ignore my comment :))

**Comment by EliasKotlyar** [comment]
Hello hostep,

I think, because i have replaced the EntityManager from the DI to the ObjectManager-Init. Therefore, the compilation should work without any problem. I think that the import should also work, because the objectmanager will hopefully return "null" if he cannot find a class.

Greetings
Elias
